version: '3.8'

services:
  grobid:
    image: lfoppiano/grobid:latest-crf
    restart: unless-stopped
    environment:
      - CONTAINER_NAME=grobid


  app:
    # build: .
    image: latexgenie/latexgenie-worker
    depends_on:
      - grobid
    environment:
      - CONTAINER_NAME=worker
      - INSTANCE_ID=1
      - REDIS_URL
      - SUPABASE_URL
      - SUPABASE_SERVICE_ROLE_KEY
    volumes:
      - ./logs:/logs

