version: '3.8'

services:
  grobid:
    image: lfoppiano/grobid:latest-crf
    restart: unless-stopped
    environment:
      - CONTAINER_NAME=grobid


  app:
    # build:
    #   context: .
    #   dockerfile: Dockerfile.cpu
    image: latexgenie/latexgenie-worker
    depends_on:
      - grobid
    environment:
      - CONTAINER_NAME=worker
      - INSTANCE_ID=1
      - REDIS_URL
      - SUPABASE_URL
      - SUPABASE_SERVICE_ROLE_KEY
    volumes:
      - ./logs:/logs

  # app:
  #   # build:
  #   #   context: .
  #   #   dockerfile: Dockerfile.gpu
  #   image: latexgenie/latexgenie-worker:gpu
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: all
  #             capabilities: [gpu]
  #   depends_on:
  #     - grobid
  #   environment:
  #     - CONTAINER_NAME=worker
  #     - INSTANCE_ID=1
  #     - REDIS_URL
  #     - SUPABASE_URL
  #     - SUPABASE_SERVICE_ROLE_KEY
  #     - NVIDIA_VISIBLE_DEVICES=all
  #   volumes:
  #     - ./logs:/logs
